name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    environment: ci
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-server

      - run: pnpm check
      - run: pnpm type-check

  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    environment: ci
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-server

      - run: pnpm build
